apiVersion: v1
kind: Namespace
metadata:
  name: c2c-opsera-sarab-ns
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: c2c-opsera-sarab-deployment
  namespace: c2c-opsera-sarab-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: 792373136340.dkr.ecr.us-east-2.amazonaws.com/cisco_pov:36d577b3c7a2930b44c56234e02087801acb9c97

---
#Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: c2c-opsera-sarab-label
  name: c2c-opsera-sarab-service
  namespace: c2c-opsera-sarab-ns
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  sessionAffinity: None
  type: LoadBalancer

---